### ISSUE TITLE
Error: Unknown directive "cost".

### ISSUE THREAD

**Issue by pontusab** [pa-bru/graphql-cost-analysis#18]
Using this with the same way spectrum does:

```
class ProtectedApolloServer extends ApolloServer {
  async createGraphQLServerOptions(req, res) {
    const options = await super.createGraphQLServerOptions(req, res)

    return {
      ...options,
      validationRules: [
        ...options.validationRules,
        costAnalysis({
          maximumCost: 10,
          defaultCost: 1,
          variables: req.body.variables,
          createError: (max, actual) => {
            const err = new ForbiddenError(
              `GraphQL query exceeds maximum complexity, please remove some nesting or fields and try again. (max: ${max}, actual: ${actual})`
            )
            return err
          },
        }),
      ],
    }
  }
}
```

But when I add `  @cost(multipliers: ["first", "last"], complexity: 5)` to my types I get the error `Error: Unknown directive "cost".`. 

Also using typescript and `ziet/ncc` to compile my backend. 

Any thoughts?

**Comment by rmoura-92** [comment]
same here since i updated a couple graphql deps, not sure where. also cacheControl but managed to fix

**Comment by simply10w** [comment]
I had the same problem in my NestJS Graphql project. NestJS uses Apollo server under the hood.

I was able to fix the issue by declaring the directive in global typedefs.

```ts
typePaths: ['./**/*.gql'],
context: () => {...},
formatError: (error) => {...},
typeDefs: [`
   directive @cost(complexity: Int, useMultipliers: Boolean, multipliers: [String]) on FIELD_DEFINITION
`],
validationRules: [...]
```

**Comment by rmoura-92** [comment]
add this to your schema
```gql
directive @cost(
    multipliers: [String],
    useMultipliers: Boolean,
    complexity: CostComplexity
  ) on OBJECT | FIELD_DEFINITION

input CostComplexity {
    min: Int = 1,
    max: Int
}
```

**Comment by blacksmoke26** [comment]
@ricardomoura By using your schema I am facing a strange issue here, Passing `complexity` value as an object doesn't override the default value. Instead of that passing `Int` works fine:

Also, the documentation uses `Int` type instead of `Object`.

Is it some kind of issue or it's just me?

The correct version should be:

```graphql
directive @cost(
  multipliers: [String],
  useMultipliers: Boolean,
  complexity: Int
) on OBJECT | FIELD_DEFINITION
```
