### ISSUE TITLE
Default useMultipliers to true if a multiplier is specified

### ISSUE THREAD

**Issue by mxstbr** [pa-bru/graphql-cost-analysis#2]
Specifying both a multiplier and having to set `useMultipliers` to true seems redundant—surely if I set a multiplier I want to use it:

```GraphQL
type Whatever {
  # 🤔
  resolver(first: Int) Something @cost(multiplier: "first", useMultipliers: true)
}
```

**Comment by pa-bru** [comment]
Hi @mxstbr , You're right. You can already do this:
```graphql
type Whatever {
  # 🤔
  resolver(first: Int) Something @cost(multiplier: "first")
}
```
The default value of `useMultipliers` is set to true.

Is that what you're talking about ?

**Comment by mxstbr** [comment]
Yep, that's exactly what I mean, awesome thanks!
