### ISSUE TITLE
Multiple multipliers?

### ISSUE THREAD

**Issue by mxstbr** [pa-bru/graphql-cost-analysis#3]
In a typical connection one can paginate both fore-and backwards with the `first` or `last` arguments, respectively. How can I tell graphql-cost-analysis that both first and last are multipliers?

```GraphQL
type Community {
  # Get a list of posts in a community
  # How can I tell graphql-cost-analysis that both first and last are multipliers?
  postConnection(first: Int, after: String, last: Int, before: String): PostConnection 
}
```

**Comment by pa-bru** [comment]
This is an interesting issue and it would be nice to be able to specify several multipliers.
What I can do is replacing multiplier string by a list of multipliers. Then I will resolve the first parameter which isn't undefined. 

For instance in your case the cost-analyzer will try to get the value of `first` and if it's undefined it will try to get `last`

Does it respond to your needs ?

**Comment by mxstbr** [comment]
I imagine it looks like this:

```GraphQL
postConnection(...): ... @cost(multipliers: ["first", "last"], complexity: 5)
```

Now users can also specify both of them so ideally `graphql-cost-analysis` would take either one of them if they are specified or add them together if both are specified.

**Comment by mxstbr** [comment]
I think you'd deprecate `multiplier` entirely since you can just as well specify only a single multiplier in the array.

**Comment by pa-bru** [comment]
Yes great suggestion :) 

I think taking either one of them in an ordered list is better than adding them together.

**Comment by mxstbr** [comment]
But then what if somebody queries

```GraphQL
{
  postConnection(first: 10, after: "", before: "", last: 10)
}
```

The query should have a cost of 5 * (10 +10) right? Not just 5 * 10.

**Comment by pa-bru** [comment]
With this example it makes no sense because you can't query first and last at the same time. you can have either the first 10 posts or the 10 last.

**Comment by mxstbr** [comment]
No you can query both and it makes sense if you need to fill up a hole in a list. https://mobile.twitter.com/leeb/status/941041670241390592

**Comment by pa-bru** [comment]
oh yes I didn't know that.

So what should be the computation of `postConnection`. I think it should be `complexity` * `number of items retrieved`

**Comment by mxstbr** [comment]
Yep exactly, so 5 * (10+10) :wink:

**Comment by pa-bru** [comment]
Okay. I will update the analyzer to take a list of multipliers and add them together if there are several.
