### ISSUE TITLE
Remove arbitrary complexity limit

### ISSUE THREAD

**Issue by mxstbr** [pa-bru/graphql-cost-analysis#4]
Why is `complexity` limited to 10? I could have an outlier query that has a complexity of 100. Why doesn't `graphql-cost-analysis` leave the complexity numbers to me?

**Comment by pa-bru** [comment]
When I did this analyzer, the purpose of this limit was to force developers to use it with caution. 

So numbers from 1 to 10 act like levels of complexity. 

However I am open to all suggestions. 

I think defining a range is useful for certain teams who collaborate in a graphql project. 

What we could do islet the user customising these numbers (and have the possibility to set null)

**Comment by mxstbr** [comment]
Yeah that would make a ton of sense to me!
